"""add promo and notify fields to orders

Revision ID: 7e5d698ab939
Revises: bfd108b930ad
Create Date: 2026-03-27 22:05:54.536129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5d698ab939'
down_revision: Union[str, Sequence[str], None] = 'bfd108b930ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('color_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('size_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('print_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_color_id'), 'orders', ['color_id'], unique=False)
    op.create_index(op.f('ix_orders_model_id'), 'orders', ['model_id'], unique=False)
    op.create_index(op.f('ix_orders_print_id'), 'orders', ['print_id'], unique=False)
    op.create_index(op.f('ix_orders_size_id'), 'orders', ['size_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'catalog_models', ['model_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'catalog_prints', ['print_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'catalog_sizes', ['size_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'catalog_colors', ['color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_size_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_print_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_model_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_color_id'), table_name='orders')
    op.drop_column('orders', 'print_id')
    op.drop_column('orders', 'size_id')
    op.drop_column('orders', 'model_id')
    op.drop_column('orders', 'color_id')
    # ### end Alembic commands ###
