"""add catalog tables

Revision ID: bfd108b930ad
Revises: 4e293a990554
Create Date: 2026-03-25 18:42:14.406234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd108b930ad'
down_revision: Union[str, Sequence[str], None] = '4e293a990554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hex_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_colors_hex_code'), 'catalog_colors', ['hex_code'], unique=False)
    op.create_index(op.f('ix_catalog_colors_id'), 'catalog_colors', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_colors_is_active'), 'catalog_colors', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_colors_name'), 'catalog_colors', ['name'], unique=True)
    op.create_table('catalog_prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('print_type', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_prints_id'), 'catalog_prints', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_prints_is_active'), 'catalog_prints', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_prints_name'), 'catalog_prints', ['name'], unique=False)
    op.create_index(op.f('ix_catalog_prints_print_type'), 'catalog_prints', ['print_type'], unique=False)
    op.create_table('catalog_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_sizes_code'), 'catalog_sizes', ['code'], unique=True)
    op.create_index(op.f('ix_catalog_sizes_id'), 'catalog_sizes', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_sizes_is_active'), 'catalog_sizes', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_sizes_sort_order'), 'catalog_sizes', ['sort_order'], unique=False)
    op.create_table('catalog_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('front_image_url', sa.String(), nullable=True),
    sa.Column('back_image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['catalog_colors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_models_color_id'), 'catalog_models', ['color_id'], unique=False)
    op.create_index(op.f('ix_catalog_models_id'), 'catalog_models', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_models_is_active'), 'catalog_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_models_name'), 'catalog_models', ['name'], unique=True)
    op.create_table('catalog_model_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['catalog_models.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['catalog_sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'size_id', name='uq_catalog_model_sizes_model_size')
    )
    op.create_index(op.f('ix_catalog_model_sizes_id'), 'catalog_model_sizes', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_model_sizes_is_active'), 'catalog_model_sizes', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_model_sizes_model_id'), 'catalog_model_sizes', ['model_id'], unique=False)
    op.create_index(op.f('ix_catalog_model_sizes_size_id'), 'catalog_model_sizes', ['size_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_model_sizes_size_id'), table_name='catalog_model_sizes')
    op.drop_index(op.f('ix_catalog_model_sizes_model_id'), table_name='catalog_model_sizes')
    op.drop_index(op.f('ix_catalog_model_sizes_is_active'), table_name='catalog_model_sizes')
    op.drop_index(op.f('ix_catalog_model_sizes_id'), table_name='catalog_model_sizes')
    op.drop_table('catalog_model_sizes')
    op.drop_index(op.f('ix_catalog_models_name'), table_name='catalog_models')
    op.drop_index(op.f('ix_catalog_models_is_active'), table_name='catalog_models')
    op.drop_index(op.f('ix_catalog_models_id'), table_name='catalog_models')
    op.drop_index(op.f('ix_catalog_models_color_id'), table_name='catalog_models')
    op.drop_table('catalog_models')
    op.drop_index(op.f('ix_catalog_sizes_sort_order'), table_name='catalog_sizes')
    op.drop_index(op.f('ix_catalog_sizes_is_active'), table_name='catalog_sizes')
    op.drop_index(op.f('ix_catalog_sizes_id'), table_name='catalog_sizes')
    op.drop_index(op.f('ix_catalog_sizes_code'), table_name='catalog_sizes')
    op.drop_table('catalog_sizes')
    op.drop_index(op.f('ix_catalog_prints_print_type'), table_name='catalog_prints')
    op.drop_index(op.f('ix_catalog_prints_name'), table_name='catalog_prints')
    op.drop_index(op.f('ix_catalog_prints_is_active'), table_name='catalog_prints')
    op.drop_index(op.f('ix_catalog_prints_id'), table_name='catalog_prints')
    op.drop_table('catalog_prints')
    op.drop_index(op.f('ix_catalog_colors_name'), table_name='catalog_colors')
    op.drop_index(op.f('ix_catalog_colors_is_active'), table_name='catalog_colors')
    op.drop_index(op.f('ix_catalog_colors_id'), table_name='catalog_colors')
    op.drop_index(op.f('ix_catalog_colors_hex_code'), table_name='catalog_colors')
    op.drop_table('catalog_colors')
    # ### end Alembic commands ###
